name: Build
on:
  push:
    branches:
      - main
      - features/build
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: sonarscan-dotnet
        uses: highbyte/sonarscan-dotnet@1.0.2
        with:
          # The key of the SonarQube project
          sonarProjectKey: pauldeen79_CsharpExpressionDumper
          # The name of the SonarQube project
          sonarProjectName: CsharpExpressionDumper
          # The name of the SonarQube organization in SonarCloud. For hosted SonarQube, skip this setting.
          sonarOrganization: pauldeen79
          dotnetBuildArguments: /home/runner/work/CsharpExpressionDumper/CsharpExpressionDumper/CsharpExpressionDumper.sln
          dotnetTestArguments: --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}